package com.castor.core.data.db.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * A single content recommendation generated by the on-device LLM.
 *
 * Persisted in Room so the user can browse recommendations offline,
 * dismiss them, or revisit earlier suggestions.
 */
@Entity(tableName = "recommendations")
data class RecommendationEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    /** Recommended title (movie / series / documentary name). */
    val title: String,
    /** Short description or synopsis. */
    val description: String = "",
    /** Primary genre of the recommended content. */
    val genre: String = "",
    /** Estimated match score (0.0–1.0) based on the taste profile. */
    val estimatedMatchScore: Float = 0f,
    /** Suggested streaming source where the content is available. */
    val source: String = "",
    /** Optional poster / thumbnail URL (nullable — may not always be available). */
    val posterUrl: String? = null,
    /** Human-readable reason explaining why this was recommended. */
    val reason: String = "",
    /** Epoch millis when the recommendation was generated. */
    val createdAt: Long = System.currentTimeMillis(),
    /** Whether the user has dismissed (swiped away) this recommendation. */
    val dismissed: Boolean = false
)
